#ifndef MAP_EDITOR_CONSTANTS_H
#define MAP_EDITOR_CONSTANTS_H

#define MAP_EDITOR_MAIN_BUTTON Qt::LeftButton
#define MAP_EDITOR_EDIT_BUTTON Qt::RightButton
#define MAP_EDITOR_CREATE_MODIFIER Qt::ControlModifier
#define MAP_EDITOR_Z_EDIT_MODIFIER Qt::ShiftModifier
#define MAP_EDITOR_RAYCAST_MOVE_MODIFIER Qt::AltModifier
#define MAP_EDITOR_ROTATE_SCALE 3.0
#define MAP_EDITOR_SCALE_SCALE 1.0
#define MAP_EDITOR_NO_DRAG_CLICK_THRESHHOLD 0.0001
#define MAP_EDITOR_LIGHT_SPHERE_RADIUS 0.30
#define MAP_EDITOR_COLOR_DISPLAY_RADIUS 8
#define MAP_EDITOR_Z_TRANSLATE_SCALE 1.0
#define MAP_EDITOR_PAINT_CELL_RADIUS 0.45
#define MAP_EDITOR_PATHNODE_LENGTH 0.4
#define MAP_EDITOR_PATHNODE_HEIGHT 0.2
#define MAP_EDITOR_PATHNODE_FLOAT_HEIGHT 0.05
#define MAP_EDITOR_PATHNODE_COLOR Color::BLUE
#define MAP_EDITOR_STARTPOINT_LENGTH 0.4
#define MAP_EDITOR_STARTPOINT_HEIGHT 0.2
#define MAP_EDITOR_STARTPOINT_FLOAT_HEIGHT 0.05
#define MAP_EDITOR_STARTPOINT_COLOR Color::RED
#define MAP_EDITOR_PATHNODE_LINK_WIDTH 2.0f
#define MAP_EDITOR_PATHNODE_LINK_START_COLOR Color::WHITE
#define MAP_EDITOR_PATHNODE_LINK_END_COLOR Color::BLUE
#define MAP_EDITOR_FINISH_PLANE_BOX_SIZE 1.0
#define MAP_EDITOR_FINISH_PLANE_COLOR Color::RED
#define MAP_EDITOR_2D_MAP_IMAGE_HEIGHT 600.0
#define CAMERA_MOVE_INC 0.25
#define CAMERA_MOVE_ORTHO_INC 0.1
#define CAMERA_MIN_ORTHO_HEIGHT 1.0
#define CAMERA_MAX_ORTHO_HEIGHT 1000.0
#define CAMERA_ORTHO_HEIGHT_INC 5.0
#define CAMERA_ORTHO_PROJECT_AXIS Y_AXIS
#define CAMERA_ORTHO_UP Point::point2D(0.0, 1.0, CAMERA_ORTHO_PROJECT_AXIS)
#define CAMERA_PERSPECTIVE_UP Point(0.0, 1.0, 0.0)
#define CAMERA_DISABLE_ORTHO_OFFSET Point(0.0, 1.5, -2.0)
#define PRECISION_SCALE_INCREMENT 0.2f
#define PRECISION_SCALE_DRAW_SCALE 15.0f
#define MIN_PRECISION_SCALE 0.1f
#define MAX_PRECISION_SCALE 5.0f
#define SELECTED_OBJECT_BOX_COLOR Color::WHITE
#define PRECISION_SCALE_HUD_DISC_COLOR Color::LIGHTGREY
#define PRECISION_SCALE_HUD_CIRCLE_COLOR Color::WHITE

#endif