#ifndef MAP_EDITOR_CONSTANTS_H
#define MAP_EDITOR_CONSTANTS_H

#define MAP_EDITOR_MAIN_BUTTON Qt::LeftButton
#define MAP_EDITOR_EDIT_BUTTON Qt::RightButton
#define MAP_EDITOR_CREATE_MODIFIER Qt::ControlModifier
#define MAP_EDITOR_NO_DRAG_CLICK_THRESHHOLD 0.0001
#define MAP_EDITOR_LIGHT_SPHERE_RADIUS 0.25
#define CAMERA_MOVE_INC 0.25
#define CAMERA_MOVE_ORTHO_INC 0.1
#define CAMERA_MIN_ORTHO_HEIGHT 1.0
#define CAMERA_MAX_ORTHO_HEIGHT 1000.0
#define CAMERA_ORTHO_HEIGHT_INC 5.0
#define CAMERA_ORTHO_PROJECT_AXIS Y_AXIS
#define CAMERA_ORTHO_UP Point::point2D(0.0, 1.0, CAMERA_ORTHO_PROJECT_AXIS)
#define CAMERA_PERSPECTIVE_UP Point(0.0, 1.0, 0.0)
#define PRECISION_SCALE_INCREMENT 0.2f
#define PRECISION_SCALE_DRAW_SCALE 15.0f
#define MIN_PRECISION_SCALE 0.1f
#define MAX_PRECISION_SCALE 5.0f
#define SELECTED_OBJECT_BOX_COLOR Color::WHITE

#endif